### ISSUE TITLE
Build error: use of unstable library feature 'renamed_spin_loop'

### ISSUE THREAD

**Issue by taeh98** [hawkw/sharded-slab#60]
Hello,

I am getting a build error when using sharded-slab v0.1.2. It was caused by "hint::spin_loop()" on line 909 in src/page/slot.rs. The error was:

error[E0658]: use of unstable library feature 'renamed_spin_loop'
   --> ...../sharded-slab-0.1.2/src/page/slot.rs:909:9

note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error: aborting due to previous error

Please could you fix the cause of this error, or let me know if you think this was caused by a mistake on my end? Thank you!

Environment info:

rustup unchanged - 1.24.3
info: latest update on 2021-07-29, rust version 1.54.0 (a178d0322 2021-07-26)

**Comment by Darksonn** [comment]
I ran in to this as well. In our case the fix appears to be to update the Rust version.

**Comment by djc** [comment]
I'm also running into this issue with Quinn's CI, which has 1.47 as the MSRV. According to the docs `std::hint::spin_loop()` was stabilized for Rust 1.49, so I don't see how the OP could have run into this issue with 1.54 (it seems to work with me with 1.54 on my local machine). I don't see any mention of a MSRV in the README or CI definition for this project; however, given that this is used in tracing and tracing still tests for 1.42, I suppose this was a mistake?

**Comment by hawkw** [comment]
Thanks, sorry about that --- I wasn't thinking when I was trying to fix the deprecation warning yesterday. Getting ready to release 0.1.3 to fix the MSRV build.

**Comment by hawkw** [comment]
Okay, I've [published v0.1.3](https://crates.io/crates/sharded-slab/0.1.3) and yanked v0.1.2. Again, sorry for the inconvenience!
