### PR TITLE
feat: Add Slab.get_mut

### LINKED ISSUE #97: `get_mut`
It'd be useful to support a `get_mut(&mut self) -> &mut` style operation, for cases where you have "parallel periods" (using `&`-self) alternating with sequential periods (using `&mut`).

### PR DESCRIPTION
**Pull request by gretchenfrage**
This commit adds a Slab::get_mut method, which takes a `&mut self`, and thus is able to get a mutable reference to an element without actually using any synchronization structures. This is a similar concept to `UnsafeCell::get_mut`, and may be useful for cases such as:

- A sharded `Slab` wrapped in a `RwLock`, such that hot path operations are done through read guards, and rarer and complex operations are done through write guards.
- Any other situation where code has both parallel and serial section, such as in fork-join systems.
- Gradually converting single-threaded systems to parallelizable systems.

The doc comment adds a test that helps ensure basic functionality works.

`test_println!` comments are not added since, as this doesn't actually manipulate any internal structures except the user-provided types, they don't seem that useful in this case.

---

Closes #97

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -623,6 +623,33 @@ impl<T, C: cfg::Config> Slab<T, C> {
         })
     }
 
+    /// Return a mutable reference to the value associated with the given key.
+    ///
+    /// This call borrows self mutably (at compile-time) which guarantees that we
```
Comment (hawkw) [inline src/lib.rs]: Teensy nit: I might format `self` in monospace here:
```suggestion
    /// This call borrows `self` mutably (at compile-time) which guarantees that we
```

File: src/shard.rs [hunk 2]
```diff
@@ -398,6 +409,11 @@ impl<T, C: cfg::Config> Ptr<T, C> {
         Some(track.get_ref())
     }
 
+    #[inline]
+    fn get_mut(&mut self) -> Option<&mut Shard<T, C>> {
+        NonNull::new(*self.0.get_mut()).map(|mut track| unsafe { track.as_mut() }.get_mut())
```
Comment (hawkw) [inline src/shard.rs]: This doesn't seem to compile on the current MSRV (Rust 1.42.0): https://github.com/hawkw/sharded-slab/actions/runs/12508005473/job/34895461998?pr=106

I believe that's because this code requires non-lexical lifetimes (NLL), which were added to the compiler in Rust 1.62.0.

I think it might be possible to rework this to return a `*mut Shard`  from the `map` so that we don't run into a lifetime issue here. But, if that's not practical, I'll freely admit that Rust 1.42.0 is now _ancient_, and it would be fine to bump the MSRV to Rust 1.62.0 for NLL, which should hopefully fix this.

Comment (hawkw) [reply src/shard.rs]: This code also does not compile under `cfg(loom)`, as `loom`'s simulated version of `AtomicPtr` doesn't have a `get_mut`. I think it would be fine for a `loom` version of this code to use the unsafe [`AtomicPtr::unsync_load`](https://docs.rs/loom/latest/loom/sync/atomic/struct.AtomicPtr.html#method.unsync_load) instead, with a comment explaining that this is okay because the `&mut self` ensures we don't actually do a racy unsynchronized access.

**Review by hawkw — CHANGES_REQUESTED** [review]
Thanks for the change! 

I definitely agree that a `get_mut()` API taking a mutable borrow makes sense and is something we ought to have.

I'll be happy to merge this once the CI build passes. Right now, it looks like there are a few issues:

- [ ] It seems [`rustfmt` needs to be run](https://github.com/hawkw/sharded-slab/actions/runs/12508005473/job/34895462555?pr=106)
- [ ] There's a compilation error on the current (admittedly, ancient) MSRV of Rust 1.42.0 due to some of the new code requiring non-lexical lifetimes. I commented on this inline.
- [ ] It looks like [the new code doesn't compile with `cfg(loom)`](https://github.com/hawkw/sharded-slab/actions/runs/12508005473/job/34895479634?pr=106), due to Loom's use of a `MutPtr<T>` type for tracking mutable accesses to `UnsafeCell<T>`s rather than returning `*mut T`, and because `loom`'s `AtomicPtr` doesn't have a `get_mut()`. I commented on some of them inline, and it should be possible to fix. 

  With that said, I don't really care about including the `get_mut` API in loom tests, since it doesn't actually exercise any concurrency. There's no way there could be the kind of race condition that `loom` is used to detect in `get_mut()`, because `get_mut()` is inherently single-threaded. So, if it's too much work to get this API to compile under `loom`, I'm fine with adding `#[cfg(not(loom)]` to the various functions that are only used to implement `get_mut`. As long as we can make the loom tests compile again, I'm fine either way.

File: src/shard.rs [hunk 3]
```diff
@@ -398,6 +416,13 @@ impl<T, C: cfg::Config> Ptr<T, C> {
         Some(track.get_ref())
     }
 
+    #[inline]
+    #[cfg(not(loom))]
+    fn get_mut(&mut self) -> Option<&mut Shard<T, C>> {
+        // MSRV: We could do `track.is_mut()`, but the current MSRV doesn't have NLL
```
Comment (hawkw) [inline src/shard.rs]: typo: i think you meant "track.as_mut()" here?

**Review by hawkw — APPROVED** [review]
Looks good to me, although I noticed one last typo. Thanks for adding this!

As an aside, you don't *need* to force push; I typically squash merge branches unless the author wants to go out of their way to rebase-merge multiple commits. Whatever workflow works for you is fine, though.

**Comment by gretchenfrage** [comment]
:)

**Comment by gretchenfrage** [comment]
All conversations should be resolved, CI passes, and there are no merge conflicts. I think this should be able to be merged

**Comment by nicola-gigante** [comment]
Hi all,

I wonder whether this PR is going to be merged after all. This is quite a blocking issue that prevents me to use the crate. Can I help in any way getting this done?
